apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-postgres-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: my-postgres-pv
  storageClassName: standard
