apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/my-postgres-pv"