---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
        - env:
            - name: POSTGRES_SERVICE_HOST
              value: postgres-service.default.svc.cluster.local
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: postgres-credentials
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-credentials
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: postgres-credentials
          image: kabalasu/translator
          imagePullPolicy: Always
          name: translator
          ports:
            - containerPort: 80
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
