apiVersion: v1
kind: Service
metadata:
  name: translator-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: tcp-80
      protocol: TCP
  selector:
    app: translator
